spec:
  destination:
    server: https://kubernetes.default.svc
  targetRevision: main
  repo: https://github.com/csun-cpointe/verify-161
  helm:
    valueFiles:
      - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated: {}

global:
  imagePullPolicy: Always
  dockerRepo: ghcr.io/