apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: hive-metastore-service
    app.kubernetes.io/name: hive-metastore-service
  name: hive-metastore-service
spec:
  {{- with .Values.service.spec.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ if .Values.service.spec.type }}
  type: {{ .Values.service.spec.type }}
  {{ end }}
  selector:
    app.kubernetes.io/instance: hive-metastore-service
    app.kubernetes.io/name: hive-metastore-service
