apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: spark-infrastructure
    app.kubernetes.io/name: spark-infrastructure
  name: spark-infrastructure
spec:
  {{- with .Values.service.spec.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ if .Values.service.spec.type }}
  type: {{ .Values.service.spec.type }}
  {{ end }}
  selector:
    app.kubernetes.io/instance: spark-infrastructure
    app.kubernetes.io/name: spark-infrastructure
