sparkApp:
    spec:
      sparkConf:
        spark.eventLog.enabled: "true"
        spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
        spark.sql.catalogImplementation: "hive"
        spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
        spark.eventLog.dir: "s3a://spark-infrastructure/spark-events"
        spark.jars.ivy: "/opt/spark/.ivy2"
