apiVersion: batch/v1
kind: Job
metadata:
  name: spark-worker-image
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: spark-worker-image
          image: boozallen/verify-161-spark-worker-docker
          command: ["echo"]
      restartPolicy: Never
